include ../config.mk

all:
clean:

install: all
	@echo Installing Rumor scripts:
	@mkdir -p $(LILYKDE)/rumor
	cp *.scm $(LILYKDE)/rumor/

uninstall:
	@echo Uninstalling Rumor scripts:
	rm -fr $(LILYKDE)/rumor
